create table if not exists users (id uuid primary key, name text, email text, location text, created_at timestamptz default now());
create table if not exists recyclers (id uuid primary key default gen_random_uuid(), name text not null, location text, accepted_items text[] not null default '{}', certification_status text not null, rating numeric(2,1), pickup_availability text, created_at timestamptz default now());
create table if not exists ewaste_items (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), item_type text not null, condition text not null, battery_present text not null, image_url text, ai_category text, ai_risk_level text, ai_recommendation text, status text not null, created_at timestamptz default now());
create table if not exists pickups (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), ewaste_item_id uuid references ewaste_items(id), recycler_id uuid references recyclers(id), address text not null, pickup_date date not null, time_slot text not null, quantity integer not null default 1, contact text, status text not null, created_at timestamptz default now());
create table if not exists certificates (id uuid primary key default gen_random_uuid(), pickup_id uuid references pickups(id) unique, certificate_number text unique not null, issued_at timestamptz default now());
insert into recyclers (name,location,accepted_items,certification_status,rating,pickup_availability) values
('GreenCircuit Recovery','Hyderabad · Demo record',array['Smartphone','Laptop','Tablet','Monitor','Printer','Keyboard','Headphones','Other Electronics'],'Demo certification record',4.8,'Same-day slots'),
('ReNew Electronics Hub','Secunderabad · Demo record',array['Smartphone','Laptop','Television','Monitor','Printer','Battery','Other Electronics'],'Demo certification record',4.7,'Next-day slots'),
('Circular Tech Works','Hyderabad · Demo record',array['Smartphone','Tablet','Headphones','Keyboard','Battery','Other Electronics'],'Demo certification record',4.6,'Flexible pickup');
