import {Check,ChevronRight,MapPin,Recycle,ShieldCheck,Truck} from 'lucide-react';
import {Button} from '../components/ui/Button';
import {Card,CardContent} from '../components/ui/Card';
import {PageHeader,StatCard,StatusBadge,EmptyState} from '../components/ui/Structure';
import type {Recycler,Pickup,PickupStatus,EwasteItem} from '../lib/types';
import type {Store} from '../lib/storage';

const statusLabels:Record<PickupStatus,string>={'Pickup Requested':'Pending','Pickup Scheduled':'Scheduled','Item Collected':'Collected','Received by Recycler':'Collected','Responsibly Recycled':'Recycled'};
const stages=['Pending','Accepted','Scheduled','Collected','Recycled'];
function stageFor(status:PickupStatus){return status==='Pickup Requested'?0:status==='Pickup Scheduled'?2:status==='Item Collected'||status==='Received by Recycler'?3:4}
function Timeline({status}:{status:PickupStatus}){const current=stageFor(status);return <div className="flex items-start gap-1">{stages.map((stage,index)=><div key={stage} className="flex min-w-0 flex-1 items-start"><div className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className={`grid h-7 w-7 place-items-center rounded-full text-xs font-semibold ${index<=current?'bg-ink text-white':'bg-cream text-slate-400'}`}>{index<current?<Check size={14}/>:index+1}</div><span className={`text-center text-[11px] ${index<=current?'font-semibold text-ink':'text-slate-400'}`}>{stage}</span></div>{index<stages.length-1&&<div className={`mt-3 h-px flex-1 ${index<current?'bg-ink':'bg-line'}`}/>}</div>)}</div>}
function actionFor(status:PickupStatus){if(status==='Pickup Requested')return {label:'Accept request',next:'Pickup Scheduled' as PickupStatus};if(status==='Pickup Scheduled')return {label:'Mark collected',next:'Item Collected' as PickupStatus};if(status==='Item Collected'||status==='Received by Recycler')return {label:'Mark recycled',next:'Responsibly Recycled' as PickupStatus};return undefined}
function RequestCard({pickup,item,onUpdate}:{pickup:Pickup;item:EwasteItem;onUpdate:(id:string,status:PickupStatus)=>void}){const action=actionFor(pickup.status);return <Card><CardContent className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Request {pickup.id.slice(-8).toUpperCase()}</p><h2 className="mt-2 text-lg font-semibold">{item.itemType}</h2><p className="mt-1 text-sm text-slate-500">{pickup.date} · {pickup.time}</p></div><StatusBadge status={statusLabels[pickup.status]}/></div><div className="grid gap-3 text-sm sm:grid-cols-3"><div><p className="text-xs text-slate-400">Condition</p><p className="mt-1 font-medium">{item.condition}</p></div><div><p className="text-xs text-slate-400">Battery</p><p className="mt-1 font-medium">{item.battery}</p></div><div><p className="text-xs text-slate-400">Pickup location</p><p className="mt-1 flex items-center gap-1 font-medium"><MapPin size={14} className="text-leaf"/>{pickup.address}</p></div></div><Timeline status={pickup.status}/>{action&&<div className="flex justify-end border-t border-line pt-4"><Button onClick={()=>onUpdate(pickup.id,action.next)}>{action.label}<ChevronRight size={16}/></Button></div>}{pickup.status==='Responsibly Recycled'&&<div className="flex items-center gap-2 border-t border-line pt-4 text-sm font-medium text-leaf"><ShieldCheck size={17}/>Eligible for disposal certificate</div>}</CardContent></Card>}
export function RecyclerDashboard({store,recycler,onUpdate,onExit}:{store:Store;recycler:Recycler;onUpdate:(id:string,status:PickupStatus)=>void;onExit:()=>void}){const pickups=store.pickups.filter(p=>p.recyclerId===recycler.id);const items=new Map(store.items.map(item=>[item.id,item]));const count=(statuses:PickupStatus[])=>pickups.filter(p=>statuses.includes(p.status)).length;return <div className="min-h-screen bg-cream"><header className="border-b border-line/80 bg-cream/90 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-white"><Recycle size={19}/></span><div><p className="font-bold">EcoLoop Recycler</p><p className="text-xs text-slate-500">Operations portal</p></div></div><Button variant="ghost" onClick={onExit}>Household view</Button></div></header><main className="mx-auto max-w-7xl space-y-8 px-5 py-8 md:py-10"><div className="flex flex-wrap items-start justify-between gap-4"><PageHeader eyebrow="Recycler dashboard" title={recycler.name} subtitle={recycler.location}/><div className="flex items-center gap-2 rounded-xl border border-leaf/20 bg-mint/60 px-3 py-2 text-sm font-semibold"><ShieldCheck size={17} className="text-leaf"/>Certified recycler</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard icon={Truck} label="New requests" value={count(['Pickup Requested'])}/><StatCard icon={Recycle} label="Scheduled pickups" value={count(['Pickup Scheduled'])}/><StatCard icon={MapPin} label="Collected" value={count(['Item Collected','Received by Recycler'])}/><StatCard icon={Check} label="Recycled" value={count(['Responsibly Recycled'])}/></div><section className="space-y-4"><div><h2 className="text-xl font-semibold tracking-tight">Incoming pickup requests</h2><p className="mt-1 text-sm text-slate-500">Move each household handoff through its next operational state.</p></div>{pickups.length===0?<EmptyState title="No pickup requests yet" description={`New requests assigned to ${recycler.name} will appear here.`}/>:pickups.slice().reverse().map(p=>{const item=items.get(p.itemId);return item?<RequestCard key={p.id} pickup={p} item={item} onUpdate={onUpdate}/>:null})}</section></main></div>}