import {ArrowRight,Clock,MapPin,ShieldCheck,SlidersHorizontal,Star,Truck} from 'lucide-react';
import {recyclers} from '../lib/demoData';
import {Card,CardContent} from '../components/ui/Card';
import {Badge} from '../components/ui/Badge';
import {Button} from '../components/ui/Button';
import {PageHeader,StepIndicator} from '../components/ui/Structure';
import type {ItemType,Recycler} from '../lib/types';

export function Recyclers({itemType,onSelect}:{itemType:ItemType;onSelect:(r:Recycler)=>void}){const ranked=[...recyclers].sort((a,b)=>Number(b.acceptedItems.includes(itemType))-Number(a.acceptedItems.includes(itemType)));return <div className="fade-in mx-auto max-w-4xl space-y-8"><PageHeader eyebrow="Step 3 of 4" title="Find a recycler" subtitle={`Trusted options for your ${itemType.toLowerCase()}, ranked by fit.`} actions={<button className="flex items-center gap-2 rounded-xl border border-line bg-white px-3 py-2 text-sm font-semibold"><SlidersHorizontal size={16}/>Sort and filter</button>}/><StepIndicator current={2} steps={['Add e-waste','AI analysis','Find recycler','Schedule pickup']}/><div className="space-y-4">{ranked.map((recycler,index)=><RecyclerCard key={recycler.id} recycler={recycler} itemType={itemType} recommended={index===0} onSelect={onSelect}/>)}</div></div>}
function RecyclerCard({recycler,itemType,recommended,onSelect}:{recycler:Recycler;itemType:ItemType;recommended:boolean;onSelect:(r:Recycler)=>void}){return <Card className={recommended?'border-leaf/40 ring-1 ring-leaf/20':''}><CardContent className="space-y-5"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-mint text-leaf"><ShieldCheck size={22}/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{recycler.name}</h2>{recommended&&<Badge>Recommended match</Badge>}</div><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin size={14}/>{recycler.location}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-600"><span className="flex items-center gap-1 rounded-full bg-cream px-2.5 py-1"><Star size={12} className="text-leaf"/>{recycler.rating} rating</span><span className="flex items-center gap-1 rounded-full bg-cream px-2.5 py-1"><Truck size={12}/>{recycler.pickupAvailability}</span><span className="rounded-full bg-cream px-2.5 py-1">{recycler.certificationStatus}</span></div></div></div><div className="flex shrink-0 gap-2 md:flex-col"><button className="rounded-xl border border-line px-3 py-2 text-sm font-semibold hover:bg-cream">View details</button><Button onClick={()=>onSelect(recycler)}>Choose recycler <ArrowRight size={15}/></Button></div></div><div className="grid gap-4 border-t border-line pt-4 text-sm sm:grid-cols-3"><div><p className="text-xs text-slate-400">Accepted categories</p><p className="mt-1 leading-6 text-slate-600">{recycler.acceptedItems.join(', ')}</p></div><div><p className="text-xs text-slate-400">Item match</p><p className="mt-1 font-semibold text-leaf">{recycler.acceptedItems.includes(itemType)?'Accepts this item':'Review accepted items'}</p></div><div><p className="text-xs text-slate-400">Processing time</p><p className="mt-1 flex items-center gap-1 font-semibold"><Clock size={14} className="text-leaf"/>Typically 2–5 days</p></div></div></CardContent></Card>}