import {Check,ChevronRight,MapPin,ShieldCheck,Truck} from 'lucide-react';
import {Card,CardContent} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {PageHeader,StatusBadge} from '../components/ui/Structure';
import type {EwasteItem,Pickup,Recycler,PickupStatus} from '../lib/types';

const steps:PickupStatus[]=['Pickup Requested','Pickup Scheduled','Item Collected','Received by Recycler','Responsibly Recycled'];
const labels=['Pickup scheduled','Pickup confirmed','Device collected','Received by recycler','Responsibly recycled'];
export function Track({pickup,item,recycler,onAdvance,onCertificate}:{pickup:Pickup;item:EwasteItem;recycler:Recycler;onAdvance:()=>void;onCertificate:()=>void}){const idx=steps.indexOf(pickup.status);return <div className="fade-in mx-auto max-w-4xl space-y-8"><PageHeader eyebrow="Disposal lifecycle" title="Track your pickup" subtitle="Follow your item through each responsible handoff." actions={<StatusBadge status={pickup.status}/>}/><div className="grid gap-5 lg:grid-cols-[1fr_.72fr]"><Card><CardContent className="md:p-8"><div className="space-y-1">{steps.map((step,index)=><div key={step} className="flex gap-4"><div className="flex flex-col items-center"><div className={`grid h-10 w-10 place-items-center rounded-full transition ${index<=idx?'bg-ink text-white':'bg-cream text-slate-400'}`}>{index<idx?<Check size={17}/>:index===idx?<Truck size={17}/>:<span className="text-xs font-semibold">{String(index+1).padStart(2,'0')}</span>}</div>{index<steps.length-1&&<div className={`h-12 w-px ${index<idx?'bg-ink':'bg-line'}`}/>}</div><div className="pt-1"><p className={`font-semibold ${index===idx?'text-ink':'text-slate-600'}`}>{labels[index]}</p><p className="mt-1 text-xs text-slate-400">{index<idx?'Completed':index===idx?'Current status':'Next step'}</p></div></div>)}</div></CardContent></Card><div className="space-y-5"><Card><CardContent><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Pickup details</p><dl className="mt-5 space-y-4 text-sm"><Row k="Pickup ID" v={pickup.id.slice(-8).toUpperCase()}/><Row k="Item" v={item.itemType}/><Row k="Recycler" v={recycler.name}/><Row k="Date" v={`${pickup.date} · ${pickup.time}`}/><Row k="Address" v={pickup.address}/></dl></CardContent></Card>{idx<steps.length-1?<Button className="w-full" onClick={onAdvance}>Demo: advance status <ChevronRight size={16}/></Button>:<Button variant="secondary" className="w-full" onClick={onCertificate}><ShieldCheck size={16}/>View disposal certificate</Button>}<p className="text-center text-xs leading-5 text-slate-500">Status updates are shown here as your recycler completes each handoff.</p></div></div></div>}
function Row({k,v}:{k:string;v:string}){return <div><dt className="text-xs text-slate-400">{k}</dt><dd className="mt-1 font-medium">{v}</dd></div>}