import {useEffect,useRef,useState} from 'react';
import {BadgeCheck,BrainCircuit,Check,ImagePlus,Truck} from 'lucide-react';

const steps=[
  {number:'01',title:'Identify',description:'Upload a clear photo of your e-waste and tell us a little about the device.',icon:ImagePlus},
  {number:'02',title:'Understand',description:'Our AI analyzes the device and explains its condition, category, and recommended handling.',icon:BrainCircuit},
  {number:'03',title:'Choose a Recycler',description:'Compare suitable certified recyclers based on location, accepted items, and available services.',icon:BadgeCheck},
  {number:'04',title:'Schedule & Track',description:'Book a pickup, follow its progress, and receive proof of responsible recycling.',icon:Truck},
];

export function HowItWorks(){const sectionRef=useRef<HTMLElement>(null);const [visible,setVisible]=useState(false);useEffect(()=>{const section=sectionRef.current;if(!section)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setVisible(true);observer.disconnect()}},{threshold:.2});observer.observe(section);return()=>observer.disconnect()},[]);return <section ref={sectionRef} id="how-it-works" className="scroll-mt-24 border-b border-line bg-white"><div className="mx-auto max-w-6xl px-5 py-20 md:py-24"><div className={`max-w-2xl transition duration-700 ${visible?'translate-y-0 opacity-100':'translate-y-4 opacity-0'}`}><p className="text-xs font-bold tracking-[.2em] text-leaf">THE ECOLOOP JOURNEY</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-ink md:text-5xl">How EcoLoop Works</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-500 md:text-lg">From identifying your device to responsible disposal, EcoLoop guides you through every step.</p></div><div className="relative mt-16 md:mt-20"><div className={`absolute left-[1.15rem] top-5 bottom-8 w-px origin-top bg-leaf/30 transition-transform duration-[1200ms] md:left-0 md:right-0 md:top-[1.15rem] md:bottom-auto md:h-px md:w-auto md:origin-left ${visible?'scale-y-100 md:scale-x-100':'scale-y-0 md:scale-x-0'}`}/><div className="relative grid gap-10 md:grid-cols-4 md:gap-0">{steps.map(({number,title,description,icon:Icon},index)=><div key={number} className={`group relative flex gap-5 transition duration-700 md:block md:px-6 md:first:pl-0 md:last:pr-0 ${index===0?'':'md:border-l md:border-transparent'} ${visible?'translate-y-0 opacity-100':'translate-y-5 opacity-0'}`} style={{transitionDelay:`${180+index*110}ms`}}><div className="relative z-10 grid h-10 w-10 shrink-0 place-items-center rounded-full border border-leaf/30 bg-white text-xs font-bold text-leaf transition duration-300 group-hover:border-ink group-hover:bg-ink group-hover:text-white md:h-11 md:w-11">{number}</div><div className="pt-0.5 md:pt-7"><div className="flex items-center gap-2 text-leaf"><Icon size={19} strokeWidth={1.7}/><span className="text-xs font-bold uppercase tracking-[.14em]">{title}</span></div><p className="mt-3 max-w-[15rem] text-sm leading-6 text-slate-500 transition duration-300 group-hover:text-slate-700">{description}</p></div>{index<steps.length-1&&<div className="absolute left-5 top-12 h-10 w-px bg-line md:hidden"/>}</div>)}</div></div></div></section>}
